if (code_point >= 0x0300 and code_point <= 0x036F)
	return false;
if (code_point >= 0x0483 and code_point <= 0x0487)
	return false;
if (code_point >= 0x0488 and code_point <= 0x0489)
	return false;
if (code_point >= 0x07EB and code_point <= 0x07F3)
	return false;
if (code_point == 0x0C00)
	return false;
if (code_point >= 0x135D and code_point <= 0x135F)
	return false;
if (code_point == 0x1A7F)
	return false;
if (code_point >= 0x1AB0 and code_point <= 0x1ABD)
	return false;
if (code_point == 0x1ABE)
	return false;
if (code_point >= 0x1B6B and code_point <= 0x1B73)
	return false;
if (code_point >= 0x1DC0 and code_point <= 0x1DF5)
	return false;
if (code_point >= 0x1DFC and code_point <= 0x1DFF)
	return false;
if (code_point >= 0x20D0 and code_point <= 0x20DC)
	return false;
if (code_point >= 0x20DD and code_point <= 0x20E0)
	return false;
if (code_point == 0x20E1)
	return false;
if (code_point >= 0x20E2 and code_point <= 0x20E4)
	return false;
if (code_point >= 0x20E5 and code_point <= 0x20F0)
	return false;
if (code_point >= 0x2CEF and code_point <= 0x2CF1)
	return false;
if (code_point >= 0x2DE0 and code_point <= 0x2DFF)
	return false;
if (code_point >= 0x3099 and code_point <= 0x309A)
	return false;
if (code_point == 0xA66F)
	return false;
if (code_point >= 0xA670 and code_point <= 0xA672)
	return false;
if (code_point >= 0xA674 and code_point <= 0xA67D)
	return false;
if (code_point >= 0xA69E and code_point <= 0xA69F)
	return false;
if (code_point >= 0xA6F0 and code_point <= 0xA6F1)
	return false;
if (code_point >= 0xA8E0 and code_point <= 0xA8F1)
	return false;
if (code_point >= 0xFE20 and code_point <= 0xFE2F)
	return false;
if (code_point == 0x101FD)
	return false;
if (code_point >= 0x10376 and code_point <= 0x1037A)
	return false;
if (code_point >= 0x11300 and code_point <= 0x11301)
	return false;
if (code_point >= 0x11366 and code_point <= 0x1136C)
	return false;
if (code_point >= 0x11370 and code_point <= 0x11374)
	return false;
if (code_point >= 0x16AF0 and code_point <= 0x16AF4)
	return false;
if (code_point == 0x1D165)
	return false;
if (code_point >= 0x1D167 and code_point <= 0x1D169)
	return false;
if (code_point >= 0x1D16E and code_point <= 0x1D172)
	return false;
if (code_point >= 0x1D17B and code_point <= 0x1D182)
	return false;
if (code_point >= 0x1D185 and code_point <= 0x1D18B)
	return false;
if (code_point >= 0x1D1AA and code_point <= 0x1D1AD)
	return false;
if (code_point >= 0x1D242 and code_point <= 0x1D244)
	return false;
if (code_point >= 0x1E8D0 and code_point <= 0x1E8D6)
	return false;
if (code_point == 0x1D166)
	return false;
if (code_point == 0x1D16D)
	return false;
