#include <vector>
#include <string>
#include "protocols/Action.hpp"
#include "protocols/Token.hpp"

#include <cstddef>

namespace tul
{
  namespace lexer
  {
    namespace dependency
    {
      /**
        The token generator uses the actions generated by the ActionGenerator
        in order to put characters into tokens. When the token is ready is
        pushes the token into a vector and signals via consumeCharacter that
        a certain number of tokens have been added.
      */
      class TokenGenerator
      {
      public:

        std::size_t consumeCharacter(char character_, protocols::Action action_);
        std::vector<protocols::Token> &getTokenStack();

      private:

        std::vector<protocols::Token> token_stack;
        std::string        current_working_lexeme;

      };
    }
  }
}
