#pragma once

namespace tul
{
  namespace protocols
  {
    enum class TokenType
    {
      GROUPER_LEFT_BRACE,
      GROUPER_RIGHT_BRACE,
      GROUPER_LEFT_BRACKET,
      GROUPER_RIGHT_BRACKET,
      GROUPER_LEFT_PARENTHESIS,
      GROUPER_RIGHT_PARENTHESIS,

      IDENTIFIER_CLASS,
      IDENTIFIER_ENUMERATION,
      IDENTIFIER_PACKAGE,
      IDENTIFIER_SUBROUTINE,
      IDENTIFIER_VARIABLE,

      INTEGER_LITERAL,

      KEYWORD_ASSEMBLY,
      KEYWORD_DO,
      KEYWORD_FOR,
      KEYWORD_GOTO,
      KEYWORD_IF,
      KEYWORD_LABEL,
      KEYWORD_PRIVATE,
      KEYWORD_PUBLIC,
      KEYWORD_RESTRICTED,
      KEYWORD_WHILE,

      PRIMITIVE_SIGNED,
      PRIMITIVE_UNSIGNED,

      STRING,

      SYMBOL_PLUS,
      SYMBOL_PLUS_PLUS,
      SYMBOL_MINUS,
      SYMBOL_MINUS_MINUS,
      SYMBOL_STAR,
      SYMBOL_STAR_STAR,
      SYMBOL_FORWARD_SLASH,
      SYMBOL_BACKWARD_SLASH,
      SYMBOL_AMPERSAND_AMPERSAND,
      SYMBOL_BAR_BAR,
      SYMBOL_AMPERSAND,
      SYMBOL_BAR,
      SYMBOL_CARET,
      SYMBOL_EXCLAMATION_MARK,
      SYMBOL_DOT_DOT,
      SYMBOL_DOT,
      SYMBOL_COMMA,
      SYMBOL_COLON_COLON,
      SYMBOL_COLON,
      SYMBOL_SEMICOLON,
      SYMBOL_LESS_THAN_LESS_THAN,
      SYMBOL_LESS_THAN,
      SYMBOL_GREATER_THAN_GREATER_THAN,
      SYMBOL_GREATER_THAN,

      UNIDENTIFIED,
    };
  }
}
