
# This file is part of Cxy Compiler Reference Implementation (Cxy CRI).
#
# Cxy CRI is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Cxy CRI is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Cxy CRI.  If not, see <http://www.gnu.org/licenses/>.
#
# # ACCESS_SPECIFIER: 1
# ADDITIVE_EXPRESSION: 3
# AND_EXPRESSION: 2
# ARGUMENT: 2
# ARGUMENT_LIST: 1
# ARGUMENT_LIST_WITH_THIS: 1
# ARRAY: 4
# ARRAY_ACCESS_EXPRESSION: 1
# ASSIGNMENT_EXPRESSION: 15
# ATTRIBUTE_LIST: 1
# ATTRIBUTE_LIST_AFTER_CONST: 1
# BASIC_TYPE: 5
# BITWISE_AND_EXPRESSION: 2
# BITWISE_OR_EXPRESSION: 2
# BITWISE_XOR_EXPRESSION: 2
# BREAK_STATEMENT: 1
# CAPTURE_LIST: 3
# CAST_EXPRESSION: 1
# CATCH_LIST: 2
# CLASS_MEMBER: 1
# CLASS_MEMBER_EXPRESSION: 1
# CODE_BLOCK: 2
# COLONIZED: 1
# COLON_LIST: 2
# CONSTRUCT_LIST: 2
# CONSTRUCT_STATEMENT: 1
# CONTINUE_STATEMENT: 1
# DATA_DECLARATION_LIST: 2
# DATA_DECLARATION_STATEMENT: 2
# DATA_DECLARATION_TYPE: 2
# DATA_NAMES: 22
# DATA_NAMES_LIST: 2
# DEBUG_STATEMENT: 1
# DEFER_STATEMENT: 1
# DELETE_EXPRESSION: 1
# DO_STATEMENT: 1
# ELSE_STATEMENT: 2
# ENTER: 1
# ENUMERABLE_TYPE: 1
# ENUMERATION_MEMBER_EXPRESSION: 1
# ENUM_EXPRESSION: 5
# ENUM_OR_NOTHING: 1
# EQUALITY_EXPRESSION: 3
# EXPRESSION_LIST: 3
# EXP_STATEMENT: 1
# FOREACH_STATEMENT: 1
# FOR_DATA_DECLARATION: 1
# FOR_STATEMENT: 1
# FUNCTION_NAMES: 2
# FUNCTION_SIGNATURE: 5
# GOTO_STATEMENT: 1
# GROUPER_LEFT_BRACE: 8
# GROUPER_LEFT_BRACKET: 11
# GROUPER_LEFT_PARENTHESIS: 17
# GROUPER_RIGHT_BRACE: 8
# GROUPER_RIGHT_BRACKET: 11
# GROUPER_RIGHT_PARENTHESIS: 17
# HACK_STATEMENT: 1
# IDENTIFIER_CLASS: 7
# IDENTIFIER_CONSTEXPR: 3
# IDENTIFIER_ENUMERATION: 4
# IDENTIFIER_PACKAGE: 6
# IDENTIFIER_SUBROUTINE: 3
# IDENTIFIER_VARIABLE: 5
# IF_STATEMENT: 1
# INTEGER_LITERAL: 1
# ITER_STATEMENT: 1
# KEYWORD_BREAK: 1
# KEYWORD_CAST: 1
# KEYWORD_CATCH: 1
# KEYWORD_CONST: 4
# KEYWORD_CONSTRUCT: 1
# KEYWORD_CONSTRUCTOR: 1
# KEYWORD_CONTINUE: 1
# KEYWORD_DEBUG: 1
# KEYWORD_DEFER: 1
# KEYWORD_DELETE: 1
# KEYWORD_DESTRUCTOR: 1
# KEYWORD_DO: 1
# KEYWORD_DOUBLE: 1
# KEYWORD_ELSE: 2
# KEYWORD_ENUM: 1
# KEYWORD_EXPERIMENTAL: 1
# KEYWORD_FLOAT: 1
# KEYWORD_FOR: 1
# KEYWORD_FOREACH: 1
# KEYWORD_GOTO: 1
# KEYWORD_HACK: 1
# KEYWORD_IF: 1
# KEYWORD_IN: 3
# KEYWORD_LABEL: 1
# KEYWORD_LAMBDA: 1
# KEYWORD_NEW: 1
# KEYWORD_PRIVATE: 1
# KEYWORD_PTR: 5
# KEYWORD_PUBLIC: 1
# KEYWORD_PURE: 2
# KEYWORD_REF: 2
# KEYWORD_RESTRICTED: 1
# KEYWORD_RETURN: 1
# KEYWORD_SIZE: 1
# KEYWORD_STATIC: 1
# KEYWORD_THIS: 3
# KEYWORD_THROW: 1
# KEYWORD_TRY: 1
# KEYWORD_TYPE: 1
# KEYWORD_VAR: 1
# KEYWORD_WHEN: 1
# KEYWORD_WHILE: 1
# LABEL_STATEMENT: 1
# MEMBER_DEFINITION: 1
# MEMBER_EXPRESSION: 3
# METHOD_DECL_OR_DEF: 1
# MULTIPLE_OR_SINGLE_CONSTRUCT: 1
# MULTIPLICATIVE_EXPRESSION: 3
# NAMEKIND: 2
# NAMES_SYMBOL: 1
# NEW_EXPRESSION: 2
# NO_SEMICOLON_STATEMENT: 2
# OPTIONAL_ADDITIVE_EXPRESSION: 1
# OPTIONAL_AND_EXPRESSION: 1
# OPTIONAL_ARGUMENT_LIST: 4
# OPTIONAL_ARGUMENT_LIST_AFTER_COMMA: 1
# OPTIONAL_ARRAY_ACCESS_EXPRESSION: 2
# OPTIONAL_ARRAY_ACCESS_EXPRESSION_AFTER_COMMA: 1
# OPTIONAL_ASSIGNMENT: 5
# OPTIONAL_ASSIGNMENT_EXPRESSION: 1
# OPTIONAL_ASSIGNMENT_MULTIVARIABLE: 1
# OPTIONAL_ASSIGNMENT_OR_CAPTURE: 1
# OPTIONAL_ATTRIBUTE_LIST: 1
# OPTIONAL_BITWISE_AND_EXPRESSION: 1
# OPTIONAL_BITWISE_OR_EXPRESSION: 1
# OPTIONAL_BITWISE_XOR_EXPRESSION: 1
# OPTIONAL_CAPTURE_LIST: 1
# OPTIONAL_COLON_LIST: 1
# OPTIONAL_COLON_LIST_AFTER_COMMA: 1
# OPTIONAL_CONSTRUCTOR_LIST: 1
# OPTIONAL_CONSTRUCT_LIST: 1
# OPTIONAL_DATA_DECLARATION: 3
# OPTIONAL_DATA_DECLARATION_AFTER_COMMA: 1
# OPTIONAL_DATA_NAMES_LIST: 1
# OPTIONAL_DATA_NAMES_LIST_AFTER_COMMA: 1
# OPTIONAL_EQUALITY_EXPRESSION: 1
# OPTIONAL_EXPRESSION: 1
# OPTIONAL_EXTRACTOR_EXPRESSION: 1
# OPTIONAL_LOOP_NAME: 5
# OPTIONAL_MEMBER_EXPRESSION: 9
# OPTIONAL_MULTIPLICATIVE_EXPRESSION: 1
# OPTIONAL_NAME: 2
# OPTIONAL_NEW_LIST: 1
# OPTIONAL_NEW_TYPE: 1
# OPTIONAL_OR_EXPRESSION: 1
# OPTIONAL_PARAMETER_LIST: 3
# OPTIONAL_PARAMETER_LIST_AFTER_COMMA: 9
# OPTIONAL_RELATIONAL_EXPRESSION: 1
# OPTIONAL_SHIFT_EXPRESSION: 1
# OPTIONAL_TEMPLATE: 3
# OPTIONAL_TEMPLATE_LIST: 5
# OPT_ASGN: 1
# OPT_COLON_ASGN: 2
# OPT_DATA_NAMES: 2
# OPT_EXP_STATEMENT: 2
# OR_EXPRESSION: 37
# PARAMETER_LIST: 1
# PRIMITIVE_SIGNED: 1
# PRIMITIVE_SIGNED_WRAPPED: 1
# PRIMITIVE_UNSIGNED: 1
# PRIMITIVE_UNSIGNED_WRAPPED: 1
# REC_DATA_NAMES: 3
# RELATIONAL_EXPRESSION: 2
# RELATIONAL_OPERATOR: 1
# RESOURCE: 1
# RETURN_STATEMENT: 2
# SHIFT_EXPRESSION: 2
# SHIFT_OPERATOR: 1
# SINGLE_CONSTRUCT: 2
# SINGLE_STATEMENT_OR_CODE_BLOCK: 9
# SIZE_EXPRESSION: 1
# STATEMENT: 2
# STATEMENT_LIST: 5
# STATIC_OR_DYNAMIC_CONTROL: 1
# STRING: 1
# SYMBOL_AMPERSAND: 1
# SYMBOL_AMPERSAND__AMPERSAND: 1
# SYMBOL_AMPERSAND__AMPERSAND__EQUAL: 1
# SYMBOL_AMPERSAND__EQUAL: 1
# SYMBOL_APETAIL: 1
# SYMBOL_BAR: 1
# SYMBOL_BAR__BAR: 1
# SYMBOL_BAR__BAR__EQUAL: 1
# SYMBOL_BAR__EQUAL: 1
# SYMBOL_CARET: 1
# SYMBOL_CARET__EQUAL: 1
# SYMBOL_COLON: 15
# SYMBOL_COMMA: 11
# SYMBOL_DOLLAR: 1
# SYMBOL_DOLLAR__DOLLAR: 1
# SYMBOL_DOT: 7
# SYMBOL_EQUAL: 7
# SYMBOL_EQUAL__EQUAL: 2
# SYMBOL_EXCLAMATION_MARK: 1
# SYMBOL_EXCLAMATION_MARK__EQUAL: 3
# SYMBOL_EXCLAMATION_MARK__EXCLAMATION_MARK: 1
# SYMBOL_EXCLAMATION_MARK__EXCLAMATION_MARK__EQUAL: 1
# SYMBOL_FORWARD_SLASH: 2
# SYMBOL_FORWARD_SLASH__EQUAL: 2
# SYMBOL_GREATER_THAN: 2
# SYMBOL_GREATER_THAN__EQUAL: 2
# SYMBOL_GREATER_THAN__GREATER_THAN: 2
# SYMBOL_GREATER_THAN__GREATER_THAN__EQUAL: 2
# SYMBOL_LESS_THAN: 2
# SYMBOL_LESS_THAN__EQUAL: 2
# SYMBOL_LESS_THAN__LESS_THAN: 2
# SYMBOL_LESS_THAN__LESS_THAN__EQUAL: 2
# SYMBOL_MINUS: 3
# SYMBOL_MINUS__EQUAL: 2
# SYMBOL_MINUS__GREATER_THAN: 1
# SYMBOL_MINUS__MINUS: 2
# SYMBOL_PERCENT: 1
# SYMBOL_PERCENT__EQUAL: 2
# SYMBOL_PLUS: 2
# SYMBOL_PLUS__EQUAL: 2
# SYMBOL_PLUS__PLUS: 2
# SYMBOL_SEMICOLON: 10
# SYMBOL_STAR: 2
# SYMBOL_STAR__EQUAL: 2
# SYMBOL_TILDE: 1
# TEMPLATE_LIST: 1
# THROW_STATEMENT: 1
# TRY_BLOCK: 1
# TYPE: 16
# TYPE_AFTER_CONST: 2
# TYPE_AFTER_PTR: 2
# TYPE_AFTER_REF: 2
# TYPE_AFTER_REF_CONST: 1
# TYPE_EXPRESSION: 5
# TYPE_OR_EXPRESSION: 2
# UNARY_EXPRESSION: 2
# UNARY_OPERATOR: 2
# VARIABLE_NAMES: 2
# VAR_OR_STATIC: 1
# WHEN_EXPRESSION: 1
# WHILE_STATEMENT: 1

productions = {
	############################################################
	'ENTER': [
		[],
		['ACCESS_SPECIFIER', 'MEMBER_DEFINITION', 'ENTER'],
	],
	############################################################
	'ACCESS_SPECIFIER': [
		[],
		['KEYWORD_PRIVATE'],
		['KEYWORD_PUBLIC'],
		['KEYWORD_RESTRICTED'],
	],
	'MEMBER_DEFINITION': [
		['DATA_DECLARATION_STATEMENT'],
		['FUNCTION_SIGNATURE', 'FUNCTION_NAMES', 'METHOD_DECL_OR_DEF'],
	],
	############################################################
	'DATA_DECLARATION_STATEMENT': [
		['DATA_DECLARATION_TYPE'],
	],
	'FUNCTION_SIGNATURE': [
		['GROUPER_LEFT_PARENTHESIS', 'ARGUMENT_LIST', 'SYMBOL_COLON', 'ARGUMENT_LIST_WITH_THIS', 'OPTIONAL_ATTRIBUTE_LIST', 'GROUPER_RIGHT_PARENTHESIS'],
	],
	'FUNCTION_NAMES': [
		['IDENTIFIER_PACKAGE'],
		['IDENTIFIER_SUBROUTINE'],
		['KEYWORD_CONSTRUCTOR'],
		['KEYWORD_DESTRUCTOR'],
		['NAMES_SYMBOL'],
	],
	'METHOD_DECL_OR_DEF': [
		['GROUPER_LEFT_BRACE', 'STATEMENT_LIST', 'GROUPER_RIGHT_BRACE'],
		['RETURN_STATEMENT', 'SYMBOL_SEMICOLON'],
		['SYMBOL_SEMICOLON'],
	],
	############################################################
	'VAR_OR_STATIC': [
		['KEYWORD_STATIC'],
		['KEYWORD_VAR'],
	],
	'DATA_DECLARATION_TYPE': [
		['TYPE', 'DATA_NAMES', 'OPTIONAL_ASSIGNMENT', 'OPTIONAL_DATA_DECLARATION', 'SYMBOL_SEMICOLON'],
	],
	'ARGUMENT_LIST': [
		[],
		['ARGUMENT', 'OPTIONAL_ARGUMENT_LIST'],
	],
	'ARGUMENT_LIST_WITH_THIS': [
		[],
		['ARGUMENT', 'OPTIONAL_ARGUMENT_LIST'],
		['KEYWORD_THIS', 'OPTIONAL_ARGUMENT_LIST'],
	],
	'OPTIONAL_ATTRIBUTE_LIST': [
		[],
		['SYMBOL_COLON', 'ATTRIBUTE_LIST'],
	],
	'NAMES_SYMBOL': [
		['SYMBOL_EQUAL__EQUAL'],
		['SYMBOL_EXCLAMATION_MARK__EQUAL'],
		['SYMBOL_FORWARD_SLASH'],
		['SYMBOL_FORWARD_SLASH__EQUAL'],
		['SYMBOL_GREATER_THAN'],
		['SYMBOL_GREATER_THAN__EQUAL'],
		['SYMBOL_GREATER_THAN__GREATER_THAN'],
		['SYMBOL_GREATER_THAN__GREATER_THAN__EQUAL'],
		['SYMBOL_LESS_THAN'],
		['SYMBOL_LESS_THAN__EQUAL'],
		['SYMBOL_LESS_THAN__LESS_THAN'],
		['SYMBOL_LESS_THAN__LESS_THAN__EQUAL'],
		['SYMBOL_MINUS'],
		['SYMBOL_MINUS__EQUAL'],
		['SYMBOL_MINUS__MINUS'],
		['SYMBOL_PERCENT'],
		['SYMBOL_PERCENT__EQUAL'],
		['SYMBOL_PLUS'],
		['SYMBOL_PLUS__EQUAL'],
		['SYMBOL_PLUS__PLUS'],
		['SYMBOL_STAR'],
		['SYMBOL_STAR__EQUAL'],
	],
	'STATEMENT_LIST': [
		[],
		['NO_SEMICOLON_STATEMENT', 'STATEMENT_LIST'],
		['STATEMENT', 'SYMBOL_SEMICOLON', 'STATEMENT_LIST'],
	],
	'RETURN_STATEMENT': [
		['KEYWORD_RETURN', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA'],
	],
	############################################################
	'DATA_DECLARATION_LIST': [
		[],
		['TYPE', 'DATA_NAMES_LIST', 'OPTIONAL_ASSIGNMENT_OR_CAPTURE', 'OPTIONAL_DATA_DECLARATION', 'SYMBOL_SEMICOLON', 'DATA_DECLARATION_LIST'],
	],
	'DATA_NAMES_LIST'
	'OPTIONAL_ASSIGNMENT_MULTIVARIABLE': [
		[],
		['SYMBOL_EQUAL', 'OR_EXPRESSION', 'SYMBOL_SEMICOLON'],
	],
	'TYPE': [
		['ARRAY'],
		['BASIC_TYPE'],
		['ENUM_EXPRESSION'],
		['FUNCTION_SIGNATURE'],
		['KEYWORD_CONST', 'TYPE_AFTER_CONST'],
		['KEYWORD_PTR', 'TYPE_AFTER_PTR'],
		['KEYWORD_REF', 'TYPE_AFTER_REF'],
		['TYPE_EXPRESSION'],
	],
	'DATA_NAMES': [
		['IDENTIFIER_CONSTEXPR'],
		['IDENTIFIER_PACKAGE'],
		['IDENTIFIER_VARIABLE'],
		['KEYWORD_IN'],
	],
	'OPTIONAL_ASSIGNMENT': [
		[],
		['GROUPER_LEFT_PARENTHESIS', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA', 'GROUPER_RIGHT_PARENTHESIS'],
		['SYMBOL_EQUAL', 'OR_EXPRESSION'],
	],
	'OPTIONAL_DATA_DECLARATION': [
		[],
		['SYMBOL_COMMA', 'OPTIONAL_DATA_DECLARATION_AFTER_COMMA'],
	],
	'ARGUMENT': [
		['TYPE', 'NAMEKIND', 'OPTIONAL_ASSIGNMENT'],
	],
	'OPTIONAL_ARGUMENT_LIST': [
		[],
		['SYMBOL_COMMA', 'OPTIONAL_ARGUMENT_LIST_AFTER_COMMA'],
	],
	'ATTRIBUTE_LIST': [
		[],
		['KEYWORD_CONST', 'ATTRIBUTE_LIST_AFTER_CONST'],
		['KEYWORD_PURE'],
	],
	'NO_SEMICOLON_STATEMENT': [
		['CODE_BLOCK'],
		['CONSTRUCT_STATEMENT'],
		['DATA_DECLARATION_STATEMENT'],
		['DEFER_STATEMENT'],
		['DO_STATEMENT'],
		['FOREACH_STATEMENT'],
		['FOR_STATEMENT'],
		['IF_STATEMENT'],
		['TRY_BLOCK'],
		['WHILE_STATEMENT'],
	],
	'STATEMENT': [
		['ASSIGNMENT_EXPRESSION'],
		['BREAK_STATEMENT'],
		['CONTINUE_STATEMENT'],
		['DEBUG_STATEMENT'],
		['EXP_STATEMENT'],
		['GOTO_STATEMENT'],
		['HACK_STATEMENT'],
		['ITER_STATEMENT'],
		['LABEL_STATEMENT'],
		['RETURN_STATEMENT'],
		['THROW_STATEMENT'],
	],
	'OPTIONAL_PARAMETER_LIST_AFTER_COMMA': [
		[],
		['PARAMETER_LIST'],
	],
	############################################################
	'OPTIONAL_ASSIGNMENT_OR_CAPTURE': [
		[],
		['COLONIZED'],
		['GROUPER_LEFT_PARENTHESIS', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA', 'GROUPER_RIGHT_PARENTHESIS'],
		['SYMBOL_EQUAL', 'OR_EXPRESSION'],
	],
	'OR_EXPRESSION': [
		['AND_EXPRESSION', 'OPTIONAL_OR_EXPRESSION'],
	],
	'ARRAY': [
		['GROUPER_LEFT_BRACKET', 'OR_EXPRESSION', 'TYPE_OR_EXPRESSION'],
	],
	'BASIC_TYPE': [
		['IDENTIFIER_CLASS', 'OPTIONAL_TEMPLATE'],
		['IDENTIFIER_PACKAGE', 'SYMBOL_DOT', 'IDENTIFIER_CLASS', 'OPTIONAL_TEMPLATE'],
		['KEYWORD_DOUBLE'],
		['KEYWORD_FLOAT'],
		['PRIMITIVE_SIGNED'],
		['PRIMITIVE_SIGNED_WRAPPED'],
		['PRIMITIVE_UNSIGNED'],
		['PRIMITIVE_UNSIGNED_WRAPPED'],
	],
	'ENUM_EXPRESSION': [
		['KEYWORD_ENUM', 'GROUPER_LEFT_BRACKET', 'ENUMERABLE_TYPE', 'GROUPER_RIGHT_BRACKET'],
	],
	'TYPE_AFTER_CONST': [
		['ARRAY'],
		['BASIC_TYPE'],
		['KEYWORD_PTR', 'TYPE'],
		['TYPE_EXPRESSION'],
	],
	'TYPE_AFTER_PTR': [
		['ARRAY'],
		['BASIC_TYPE'],
		['ENUM_EXPRESSION'],
		['FUNCTION_SIGNATURE'],
		['KEYWORD_CONST', 'TYPE_AFTER_CONST'],
		['KEYWORD_PTR', 'TYPE_AFTER_PTR'],
		['KEYWORD_REF', 'TYPE_AFTER_REF'],
		['TYPE_EXPRESSION'],
	],
	'TYPE_AFTER_REF': [
		['ARRAY'],
		['BASIC_TYPE'],
		['ENUM_EXPRESSION'],
		['FUNCTION_SIGNATURE'],
		['KEYWORD_CONST', 'TYPE_AFTER_REF_CONST'],
		['KEYWORD_PTR', 'TYPE'],
		['TYPE_EXPRESSION'],
	],
	'TYPE_EXPRESSION': [
		['KEYWORD_TYPE', 'GROUPER_LEFT_BRACKET', 'VARIABLE_NAMES', 'GROUPER_RIGHT_BRACKET', 'OPTIONAL_TEMPLATE'],
	],
	'OPTIONAL_DATA_DECLARATION_AFTER_COMMA': [
		[],
		['DATA_NAMES', 'OPTIONAL_ASSIGNMENT', 'OPTIONAL_DATA_DECLARATION'],
	],
	'NAMEKIND': [
		['DATA_NAMES'],
		['GROUPER_LEFT_BRACE', 'DATA_NAMES_LIST', 'GROUPER_RIGHT_BRACE'],
	],
	'OPTIONAL_ARGUMENT_LIST_AFTER_COMMA': [
		[],
		['TYPE', 'NAMEKIND', 'OPTIONAL_ASSIGNMENT', 'OPTIONAL_ARGUMENT_LIST'],
	],
	'ATTRIBUTE_LIST_AFTER_CONST': [
		[],
		['KEYWORD_PURE'],
	],
	'CODE_BLOCK': [
		['GROUPER_LEFT_BRACE', 'STATEMENT_LIST', 'GROUPER_RIGHT_BRACE'],
	],
	'CONSTRUCT_STATEMENT': [
		['KEYWORD_CONSTRUCT', 'MULTIPLE_OR_SINGLE_CONSTRUCT'],
	],
	'DEFER_STATEMENT': [
		['KEYWORD_DEFER', 'SINGLE_STATEMENT_OR_CODE_BLOCK'],
	],
	'DO_STATEMENT': [
		['KEYWORD_DO', 'OPTIONAL_LOOP_NAME', 'GROUPER_LEFT_PARENTHESIS', 'ASSIGNMENT_EXPRESSION', 'GROUPER_RIGHT_PARENTHESIS', 'SINGLE_STATEMENT_OR_CODE_BLOCK'],
	],
	'FOREACH_STATEMENT': [
		['KEYWORD_FOREACH', 'OPTIONAL_LOOP_NAME', 'GROUPER_LEFT_PARENTHESIS', 'TYPE', 'DATA_NAMES', 'KEYWORD_IN', 'OR_EXPRESSION', 'GROUPER_RIGHT_PARENTHESIS', 'SINGLE_STATEMENT_OR_CODE_BLOCK'],
	],
	'FOR_STATEMENT': [
		['KEYWORD_FOR', 'OPTIONAL_LOOP_NAME', 'GROUPER_LEFT_PARENTHESIS', 'FOR_DATA_DECLARATION', 'ASSIGNMENT_EXPRESSION', 'SYMBOL_SEMICOLON', 'STATEMENT_LIST', 'GROUPER_RIGHT_PARENTHESIS', 'SINGLE_STATEMENT_OR_CODE_BLOCK'],
	],
	'IF_STATEMENT': [
		['KEYWORD_IF', 'OPTIONAL_LOOP_NAME', 'STATIC_OR_DYNAMIC_CONTROL', 'SINGLE_STATEMENT_OR_CODE_BLOCK', 'ELSE_STATEMENT'],
	],
	'TRY_BLOCK': [
		['KEYWORD_TRY', 'SINGLE_STATEMENT_OR_CODE_BLOCK', 'CATCH_LIST'],
	],
	'WHILE_STATEMENT': [
		['KEYWORD_WHILE', 'OPTIONAL_LOOP_NAME', 'ASSIGNMENT_EXPRESSION', 'SINGLE_STATEMENT_OR_CODE_BLOCK', 'ELSE_STATEMENT'],
	],
	'ASSIGNMENT_EXPRESSION': [
		['OR_EXPRESSION', 'OPTIONAL_ASSIGNMENT_EXPRESSION'],
	],
	'BREAK_STATEMENT': [
		['KEYWORD_BREAK', 'OPTIONAL_NAME'],
	],
	'CONTINUE_STATEMENT': [
		['KEYWORD_CONTINUE', 'OPTIONAL_NAME'],
	],
	'DEBUG_STATEMENT': [
		['KEYWORD_DEBUG', 'ASSIGNMENT_EXPRESSION'],
	],
	'EXP_STATEMENT': [
		['KEYWORD_EXPERIMENTAL', 'OR_EXPRESSION', 'OPT_DATA_NAMES', 'OPT_EXP_STATEMENT', 'OPT_ASGN'],
	],
	'GOTO_STATEMENT': [
		['KEYWORD_GOTO', 'DATA_NAMES'],
	],
	'HACK_STATEMENT': [
		['KEYWORD_HACK', 'GROUPER_LEFT_PARENTHESIS', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA', 'GROUPER_RIGHT_PARENTHESIS'],
	],
	'ITER_STATEMENT': [
		['SYMBOL_MINUS__MINUS', 'OR_EXPRESSION'],
		['SYMBOL_PLUS__PLUS', 'OR_EXPRESSION'],
	],
	'LABEL_STATEMENT': [
		['KEYWORD_LABEL', 'DATA_NAMES'],
	],
	'THROW_STATEMENT': [
		['KEYWORD_THROW', 'ENUM_OR_NOTHING'],
	],
	'PARAMETER_LIST': [
		['DATA_NAMES', 'SYMBOL_COLON', 'OR_EXPRESSION', 'OPTIONAL_PARAMETER_LIST'],
		['GROUPER_LEFT_BRACE', 'COLON_LIST', 'GROUPER_RIGHT_BRACE', 'SYMBOL_COLON', 'OR_EXPRESSION', 'OPTIONAL_PARAMETER_LIST'],
		['SYMBOL_COLON', 'OR_EXPRESSION', 'OPTIONAL_PARAMETER_LIST'],
	],
	############################################################
	'COLONIZED': [
		['SYMBOL_COLON', 'DATA_NAMES'],
	],
	'AND_EXPRESSION': [
		['BITWISE_OR_EXPRESSION', 'OPTIONAL_AND_EXPRESSION'],
	],
	'OPTIONAL_OR_EXPRESSION': [
		[],
		['SYMBOL_BAR__BAR', 'OR_EXPRESSION'],
	],
	'TYPE_OR_EXPRESSION': [
		['SYMBOL_COLON', 'OR_EXPRESSION', 'TYPE_OR_EXPRESSION'],
		['SYMBOL_COMMA', 'TYPE', 'GROUPER_RIGHT_BRACKET'],
	],
	'OPTIONAL_TEMPLATE': [
		[],
		['GROUPER_LEFT_BRACKET', 'TEMPLATE_LIST', 'GROUPER_RIGHT_BRACKET'],
	],
	'ENUMERABLE_TYPE': [
		['IDENTIFIER_CLASS'],
		['IDENTIFIER_PACKAGE', 'SYMBOL_DOT', 'IDENTIFIER_CLASS'],
		['TYPE_EXPRESSION'],
	],
	'TYPE_AFTER_REF_CONST': [
		['BASIC_TYPE'],
		['ENUM_EXPRESSION'],
		['KEYWORD_PTR', 'TYPE'],
	],
	'VARIABLE_NAMES': [
		['FUNCTION_NAMES'],
		['IDENTIFIER_VARIABLE'],
		['KEYWORD_THIS'],
	],
	'DATA_NAMES_LIST': [
		['DATA_NAMES', 'OPTIONAL_ASSIGNMENT', 'OPTIONAL_DATA_NAMES_LIST'],
	],
	'MULTIPLE_OR_SINGLE_CONSTRUCT': [
		['GROUPER_LEFT_BRACE', 'CONSTRUCT_LIST', 'GROUPER_RIGHT_BRACE'],
		['SINGLE_CONSTRUCT'],
	],
	'SINGLE_STATEMENT_OR_CODE_BLOCK': [
		['NO_SEMICOLON_STATEMENT'],
		['STATEMENT', 'SYMBOL_SEMICOLON'],
	],
	'OPTIONAL_LOOP_NAME': [
		[],
		['DATA_NAMES'],
	],
	'FOR_DATA_DECLARATION': [
		['DATA_DECLARATION_TYPE'],
		['SYMBOL_SEMICOLON'],
	],
	'STATIC_OR_DYNAMIC_CONTROL': [
		['GROUPER_LEFT_BRACKET', 'ASSIGNMENT_EXPRESSION', 'GROUPER_RIGHT_BRACKET'],
		['GROUPER_LEFT_PARENTHESIS', 'ASSIGNMENT_EXPRESSION', 'GROUPER_RIGHT_PARENTHESIS'],
	],
	'ELSE_STATEMENT': [
		[],
		['KEYWORD_ELSE', 'SINGLE_STATEMENT_OR_CODE_BLOCK'],
	],
	'CATCH_LIST': [
		[],
		['KEYWORD_CATCH', 'GROUPER_LEFT_PARENTHESIS', 'ENUM_EXPRESSION', 'SYMBOL_DOT', 'IDENTIFIER_ENUMERATION', 'GROUPER_RIGHT_PARENTHESIS', 'SINGLE_STATEMENT_OR_CODE_BLOCK', 'CATCH_LIST'],
	],
	'OPTIONAL_ASSIGNMENT_EXPRESSION': [
		[],
		['SYMBOL_AMPERSAND__AMPERSAND__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_AMPERSAND__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_BAR__BAR__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_BAR__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_CARET__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_EXCLAMATION_MARK__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_EXCLAMATION_MARK__EXCLAMATION_MARK__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_FORWARD_SLASH__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_GREATER_THAN__GREATER_THAN__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_LESS_THAN__LESS_THAN__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_MINUS__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_PERCENT__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_PLUS__EQUAL', 'OR_EXPRESSION'],
		['SYMBOL_STAR__EQUAL', 'OR_EXPRESSION'],
	],
	'OPTIONAL_NAME': [
		[],
		['DATA_NAMES'],
	],
	'OPT_DATA_NAMES': [
		[],
		['DATA_NAMES', 'OPT_COLON_ASGN'],
		['GROUPER_LEFT_BRACE', 'REC_DATA_NAMES', 'GROUPER_RIGHT_BRACE'],
		['SYMBOL_COLON', 'DATA_NAMES'],
		['SYMBOL_EQUAL', 'OR_EXPRESSION'],
	],
	'OPT_EXP_STATEMENT': [
		[],
		['SYMBOL_COMMA', 'OR_EXPRESSION', 'OPT_DATA_NAMES', 'OPT_EXP_STATEMENT'],
	],
	'OPT_ASGN': [
		[],
		['SYMBOL_EQUAL', 'OR_EXPRESSION'],
	],
	'ENUM_OR_NOTHING': [
		[],
		['IDENTIFIER_ENUMERATION'],
	],
	'OPTIONAL_PARAMETER_LIST': [
		[],
		['SYMBOL_COMMA', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA'],
	],
	'COLON_LIST': [
		['DATA_NAMES', 'SYMBOL_COLON', 'DATA_NAMES', 'OPTIONAL_COLON_LIST'],
	],
	############################################################
	'BITWISE_OR_EXPRESSION': [
		['BITWISE_XOR_EXPRESSION', 'OPTIONAL_BITWISE_OR_EXPRESSION'],
	],
	'OPTIONAL_AND_EXPRESSION': [
		[],
		['SYMBOL_AMPERSAND__AMPERSAND', 'AND_EXPRESSION'],
	],
	'TEMPLATE_LIST': [
		['IDENTIFIER_CLASS', 'SYMBOL_COLON', 'TYPE', 'OPTIONAL_TEMPLATE_LIST'],
		['IDENTIFIER_CONSTEXPR', 'SYMBOL_COLON', 'OR_EXPRESSION', 'OPTIONAL_TEMPLATE_LIST'],
		['SYMBOL_COLON', 'TYPE', 'OPTIONAL_TEMPLATE_LIST'],
	],
	'OPTIONAL_DATA_NAMES_LIST': [
		[],
		['OPTIONAL_DATA_NAMES_LIST_AFTER_COMMA'],
	],
	'CONSTRUCT_LIST': [
		['SINGLE_CONSTRUCT', 'OPTIONAL_CONSTRUCT_LIST'],
	],
	'SINGLE_CONSTRUCT': [
		['DATA_NAMES', 'GROUPER_LEFT_PARENTHESIS', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA', 'GROUPER_RIGHT_PARENTHESIS', 'SYMBOL_SEMICOLON'],
	],
	'OPT_COLON_ASGN': [
		[],
		['NEW_EXPRESSION'],
		['SYMBOL_COLON', 'DATA_NAMES'],
		['SYMBOL_EQUAL', 'OR_EXPRESSION'],
	],
	'REC_DATA_NAMES': [
		[],
		['DATA_NAMES', 'OPT_COLON_ASGN', 'REC_DATA_NAMES'],
		['SYMBOL_COMMA', 'REC_DATA_NAMES'],
	],
	'OPTIONAL_COLON_LIST': [
		[],
		['SYMBOL_COMMA', 'OPTIONAL_COLON_LIST_AFTER_COMMA'],
	],
	############################################################
	'BITWISE_XOR_EXPRESSION': [
		['BITWISE_AND_EXPRESSION', 'OPTIONAL_BITWISE_XOR_EXPRESSION'],
	],
	'OPTIONAL_BITWISE_OR_EXPRESSION': [
		[],
		['SYMBOL_BAR', 'BITWISE_OR_EXPRESSION'],
	],
	'OPTIONAL_TEMPLATE_LIST': [
		[],
		['IDENTIFIER_CLASS', 'SYMBOL_COLON', 'TYPE', 'OPTIONAL_TEMPLATE_LIST'],
		['SYMBOL_COLON', 'TYPE', 'OPTIONAL_TEMPLATE_LIST'],
	],
	'OPTIONAL_DATA_NAMES_LIST_AFTER_COMMA': [
		[],
		['DATA_NAMES_LIST'],
	],
	'OPTIONAL_CONSTRUCT_LIST': [
		[],
		['CONSTRUCT_LIST'],
	],
	'NEW_EXPRESSION': [
		['KEYWORD_NEW', 'OPTIONAL_NEW_TYPE', 'OPTIONAL_NEW_LIST', 'OPTIONAL_CONSTRUCTOR_LIST'],
	],
	'OPTIONAL_COLON_LIST_AFTER_COMMA': [
		[],
		['COLON_LIST'],
	],
	############################################################
	'BITWISE_AND_EXPRESSION': [
		['EQUALITY_EXPRESSION', 'OPTIONAL_BITWISE_AND_EXPRESSION'],
	],
	'OPTIONAL_BITWISE_XOR_EXPRESSION': [
		[],
		['SYMBOL_CARET', 'BITWISE_XOR_EXPRESSION'],
	],
	'OPTIONAL_NEW_TYPE': [
		[],
		['GROUPER_LEFT_BRACKET', 'TYPE', 'GROUPER_RIGHT_BRACKET'],
	],
	'OPTIONAL_NEW_LIST': [
		[],
		['GROUPER_LEFT_PARENTHESIS', 'ASSIGNMENT_EXPRESSION', 'OPTIONAL_EXPRESSION', 'GROUPER_RIGHT_PARENTHESIS'],
	],
	'OPTIONAL_CONSTRUCTOR_LIST': [
		[],
		['GROUPER_LEFT_BRACE', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA', 'GROUPER_RIGHT_BRACE'],
	],
	############################################################
	'EQUALITY_EXPRESSION': [
		['RELATIONAL_EXPRESSION', 'OPTIONAL_EQUALITY_EXPRESSION'],
	],
	'OPTIONAL_BITWISE_AND_EXPRESSION': [
		[],
		['SYMBOL_AMPERSAND', 'BITWISE_AND_EXPRESSION'],
	],
	'OPTIONAL_EXPRESSION': [
		[],
		['SYMBOL_COMMA', 'ASSIGNMENT_EXPRESSION'],
	],
	############################################################
	'RELATIONAL_EXPRESSION': [
		['SHIFT_EXPRESSION', 'OPTIONAL_RELATIONAL_EXPRESSION'],
	],
	'OPTIONAL_EQUALITY_EXPRESSION': [
		[],
		['SYMBOL_EQUAL__EQUAL', 'EQUALITY_EXPRESSION'],
		['SYMBOL_EXCLAMATION_MARK__EQUAL', 'EQUALITY_EXPRESSION'],
	],
	############################################################
	'SHIFT_EXPRESSION': [
		['ADDITIVE_EXPRESSION', 'OPTIONAL_SHIFT_EXPRESSION'],
	],
	'OPTIONAL_RELATIONAL_EXPRESSION': [
		[],
		['RELATIONAL_OPERATOR', 'RELATIONAL_EXPRESSION'],
	],
	############################################################
	'ADDITIVE_EXPRESSION': [
		['MULTIPLICATIVE_EXPRESSION', 'OPTIONAL_ADDITIVE_EXPRESSION'],
	],
	'OPTIONAL_SHIFT_EXPRESSION': [
		[],
		['SHIFT_OPERATOR', 'SHIFT_EXPRESSION'],
	],
	'RELATIONAL_OPERATOR': [
		['SYMBOL_GREATER_THAN'],
		['SYMBOL_GREATER_THAN__EQUAL'],
		['SYMBOL_LESS_THAN'],
		['SYMBOL_LESS_THAN__EQUAL'],
	],
	############################################################
	'MULTIPLICATIVE_EXPRESSION': [
		['UNARY_EXPRESSION', 'OPTIONAL_MULTIPLICATIVE_EXPRESSION'],
	],
	'OPTIONAL_ADDITIVE_EXPRESSION': [
		[],
		['SYMBOL_MINUS', 'ADDITIVE_EXPRESSION'],
		['SYMBOL_PLUS', 'ADDITIVE_EXPRESSION'],
	],
	'SHIFT_OPERATOR': [
		['SYMBOL_GREATER_THAN__GREATER_THAN'],
		['SYMBOL_LESS_THAN__LESS_THAN'],
	],
	############################################################
	'UNARY_EXPRESSION': [
		['CAST_EXPRESSION'],
		['DELETE_EXPRESSION'],
		['MEMBER_EXPRESSION'],
		['NEW_EXPRESSION'],
		['SIZE_EXPRESSION'],
		['UNARY_OPERATOR', 'UNARY_EXPRESSION'],
	],
	'OPTIONAL_MULTIPLICATIVE_EXPRESSION': [
		[],
		['SYMBOL_FORWARD_SLASH', 'MULTIPLICATIVE_EXPRESSION'],
		['SYMBOL_STAR', 'MULTIPLICATIVE_EXPRESSION'],
	],
	############################################################
	'CAST_EXPRESSION': [
		['KEYWORD_CAST', 'GROUPER_LEFT_BRACKET', 'TYPE', 'GROUPER_RIGHT_BRACKET', 'GROUPER_LEFT_PARENTHESIS', 'ASSIGNMENT_EXPRESSION', 'GROUPER_RIGHT_PARENTHESIS'],
	],
	'DELETE_EXPRESSION': [
		['KEYWORD_DELETE', 'GROUPER_LEFT_PARENTHESIS', 'ASSIGNMENT_EXPRESSION', 'GROUPER_RIGHT_PARENTHESIS'],
	],
	'MEMBER_EXPRESSION': [
		['IDENTIFIER_CLASS', 'CLASS_MEMBER_EXPRESSION'],
		['IDENTIFIER_CONSTEXPR', 'OPTIONAL_MEMBER_EXPRESSION'],
		['IDENTIFIER_ENUMERATION', 'ENUMERATION_MEMBER_EXPRESSION'],
		['IDENTIFIER_PACKAGE', 'OPTIONAL_MEMBER_EXPRESSION'],
		['IDENTIFIER_SUBROUTINE', 'OPTIONAL_MEMBER_EXPRESSION'],
		['IDENTIFIER_VARIABLE', 'OPTIONAL_MEMBER_EXPRESSION'],
		['RESOURCE', 'OPTIONAL_MEMBER_EXPRESSION'],
	],
	'SIZE_EXPRESSION': [
		['KEYWORD_SIZE', 'GROUPER_LEFT_BRACKET', 'TYPE', 'GROUPER_RIGHT_BRACKET'],
	],
	'UNARY_OPERATOR': [
		['SYMBOL_APETAIL'],
		['SYMBOL_DOLLAR'],
		['SYMBOL_DOLLAR__DOLLAR'],
		['SYMBOL_EXCLAMATION_MARK'],
		['SYMBOL_EXCLAMATION_MARK__EXCLAMATION_MARK'],
		['SYMBOL_MINUS'],
	],
	############################################################
	'CLASS_MEMBER_EXPRESSION': [
		[],
		['GROUPER_LEFT_PARENTHESIS', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA', 'GROUPER_RIGHT_PARENTHESIS'],
		['SYMBOL_DOT', 'CLASS_MEMBER', 'OPTIONAL_MEMBER_EXPRESSION'],
	],
	'OPTIONAL_MEMBER_EXPRESSION': [
		[],
		['ARRAY_ACCESS_EXPRESSION'],
		['GROUPER_LEFT_PARENTHESIS', 'OPTIONAL_PARAMETER_LIST_AFTER_COMMA', 'GROUPER_RIGHT_PARENTHESIS', 'OPTIONAL_EXTRACTOR_EXPRESSION'],
		['SYMBOL_DOT', 'MEMBER_EXPRESSION'],
		['SYMBOL_MINUS__GREATER_THAN', 'MEMBER_EXPRESSION'],
	],
	'ENUMERATION_MEMBER_EXPRESSION': [
		[],
		['SYMBOL_DOT', 'IDENTIFIER_VARIABLE'],
	],
	'RESOURCE': [
		['GROUPER_LEFT_BRACKET', 'EXPRESSION_LIST', 'GROUPER_RIGHT_BRACKET'],
		['GROUPER_LEFT_PARENTHESIS', 'ASSIGNMENT_EXPRESSION', 'GROUPER_RIGHT_PARENTHESIS'],
		['INTEGER_LITERAL'],
		['KEYWORD_IN'],
		['KEYWORD_LAMBDA', 'OPTIONAL_CAPTURE_LIST', 'FUNCTION_SIGNATURE', 'CODE_BLOCK'],
		['KEYWORD_THIS'],
		['STRING'],
		['WHEN_EXPRESSION'],
	],
	############################################################
	'CLASS_MEMBER': [
		['IDENTIFIER_ENUMERATION'],
		['IDENTIFIER_PACKAGE'],
		['IDENTIFIER_SUBROUTINE'],
		['IDENTIFIER_VARIABLE'],
	],
	'ARRAY_ACCESS_EXPRESSION': [
		['GROUPER_LEFT_BRACKET', 'ASSIGNMENT_EXPRESSION', 'OPTIONAL_ARRAY_ACCESS_EXPRESSION', 'GROUPER_RIGHT_BRACKET', 'OPTIONAL_MEMBER_EXPRESSION'],
	],
	'OPTIONAL_EXTRACTOR_EXPRESSION': [
		[],
		['SYMBOL_DOT', 'VARIABLE_NAMES', 'OPTIONAL_MEMBER_EXPRESSION'],
		['SYMBOL_TILDE', 'DATA_NAMES', 'OPTIONAL_MEMBER_EXPRESSION'],
	],
	'EXPRESSION_LIST': [
		[],
		['ASSIGNMENT_EXPRESSION', 'EXPRESSION_LIST'],
		['SYMBOL_COMMA', 'EXPRESSION_LIST'],
	],
	'OPTIONAL_CAPTURE_LIST': [
		[],
		['GROUPER_LEFT_BRACKET', 'CAPTURE_LIST', 'GROUPER_RIGHT_BRACKET'],
	],
	'WHEN_EXPRESSION': [
		['KEYWORD_WHEN', 'GROUPER_LEFT_PARENTHESIS', 'OR_EXPRESSION', 'GROUPER_RIGHT_PARENTHESIS', 'OR_EXPRESSION', 'KEYWORD_ELSE', 'OR_EXPRESSION'],
	],
	############################################################
	'OPTIONAL_ARRAY_ACCESS_EXPRESSION': [
		[],
		['SYMBOL_COMMA', 'OPTIONAL_ARRAY_ACCESS_EXPRESSION_AFTER_COMMA'],
	],
	'CAPTURE_LIST': [
		[],
		['DATA_NAMES', 'CAPTURE_LIST'],
		['UNARY_OPERATOR', 'DATA_NAMES', 'CAPTURE_LIST'],
	],
	############################################################
	'OPTIONAL_ARRAY_ACCESS_EXPRESSION_AFTER_COMMA': [
		[],
		['ASSIGNMENT_EXPRESSION', 'OPTIONAL_ARRAY_ACCESS_EXPRESSION'],
	],

}
